// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Studio.Mac
{
	public partial class Editor : NSTextView
	{
		public Editor (IntPtr handle) : base (handle)
		{
		}
	}
}
