// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;

namespace Studio.Mac
{
    [Register("EditorTextView")]
	public partial class EditorTextView : NSTextView
	{
		public EditorTextView (IntPtr handle) : base (handle)
		{
		}
	}
}
